apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pgi-les-hendelse-skatt
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  image: {{ image }}
  team: pensjonopptjening
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "skatteetaten:pensjonsgivendeinntektforfolketrygden"
  envFrom:
    - secret: pgi-les-hendelse-skatt-secrets
  liveness:
    path: isAlive
    initialDelay: 5
  readiness:
    path: isReady
    initialDelay: 5
  replicas:
    min: 1
    max: 1
  env:
    - name: APP_TEAM
      value: pensjonopptjening
    - name: SKATT_HENDELSE_PATH
      value: /api/formueinntekt/pensjonsgivendeinntektforfolketrygden/hendelser/
    - name: SKATT_HENDELSE_START_PATH
      value: /api/formueinntekt/pensjonsgivendeinntektforfolketrygden/hendelser/start
  accessPolicy:
    outbound:
      external:
        - host: api-test.sits.no
