apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pgi-les-hendelse-skatt
  namespace: default
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: isAlive
    initialDelay: 30
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: isReady
    initialDelay: 30
    periodSeconds: 1
    failureThreshold: 60
  replicas:
    min: 1
    max: 1

