apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pgi-les-hendelse-skatt
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  image: {{ image }}
  port: 8080
  kafka:
    pool: nav-dev
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "skatteetaten:pensjonsgivendeinntektforfolketrygden"
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 50
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 50
  prometheus:
    enabled: true
    path: /actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  replicas:
    min: 1
    max: 1
  env:
    - name: APP_TEAM
      value: pensjonopptjening
    - name: GRUNNLAG_PGI_HENDELSE_HOST
      value: https://pgiforfolketrygdenhendelser.api.skatteetaten-test.no
    - name: GRUNNLAG_PGI_FIRST_SEKVENSNUMMER_HOST
      value: https://pgiforfolketrygdenhendelser.api.skatteetaten-test.no
    - name: SKATT_HENDELSE_PATH
      value: /v1/hendelser
    - name: SKATT_HENDELSE_START_PATH
      value: /v1/hendelser/start
    - name: DELAY_IN_SECONDS_BEFORE_POLLING_SKATT
      value: "30"
#    - name: TILBAKESTILL_SEKVENSNUMMER
#      value: "false"
#    - name: TILBAKESTILL_SEKVENSNUMMER_TIL
#      value: "2023-06-01"
  accessPolicy:
    outbound:
      external:
        - host: pgiforfolketrygdenhendelser.api.skatteetaten-test.no
