apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pgi-les-hendelse-skatt
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  team: pensjonsamhandling
  port: 8080
  kafka:
    pool: nav-dev
  envFrom:
    - secret: pgi-les-hendelse-skatt-secrets
  liveness:
    path: isAlive
    initialDelay: 5
  readiness:
    path: isReady
    initialDelay: 5
  replicas:
    min: 1
    max: 1
  env:
    - name: APP_TEAM
      value: pensjonsamhandling
  accessPolicy:
    outbound:
      rules:
        - application: pgi-mock