name: GCP NAIS Deploy prod

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-to-prod:
    name: Deploy to prod-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Java 21'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 'Build artifact'
        run: |
          ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push docker image'
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: pensjonopptjening
          tag: ${{ github.sha }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # required, but is defined as an organization variable
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # required, but is defined as an organization secret

      - name: 'Deploy pgi-les-hendelse-skatt (prod-gcp)'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: gcp-nais-prod.yaml,alerts.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}
          TELEMETRY: ${{ steps.docker-push.outputs.telemetry }}